### ISSUE TITLE
Modular features

### ISSUE THREAD

**Issue by isaactopo** [andri/fluidable#10]
Hi Andri!
I was thinking it would be interesting to include features such as “fixed aspect ratio” as modules with @import because it is something that is not used in all projects and keep the total weight of the grid to the minimum.
It's only a thought, thanks for this great Grid!

**Comment by andri** [comment]
I'll look into this, but I'm not sure if thats a viable option with out moving those features into a separate repository. Many developers are using Bower for an example so the solution would have to work without changing the LESS file itself. We want people to be able to upgrade without reconfiguring.

Maybe we could move the config into a separate file similar to Twitter Bootstrap and then add this option somehow.  If you have an idea how to achieve this I would love to hear it.

**Comment by isaactopo** [comment]
You can have 3 files all on the same repository(for example):
fluidable.less with:
```css
@import 'grid.less';
@import 'aspect-ratio.less';
```
With that in production you can comment features if you don't use it:
```css
@import 'grid.less';
/* @import 'aspect-ratio.less'; */
```
What do you think?

**Comment by andri** [comment]
Yeah its not as complicated as I thought at first. I'll do an update (Milestone 1.3) next month including this and some other small fixes.

**Comment by isaactopo** [comment]
Awesome, thanks!
