### ISSUE TITLE
horizontal scrollbars

### ISSUE THREAD

**Issue by commonpike** [andri/fluidable#13]
great code !

removing the outer padding by doing a 
<code>
.col-group { margin-right: @gutterWidth / -2; }
</code>

is causing horizontal scrollbars to appear in chrome (in certain circumstances). you could try something with :last-child, :first-child, but thats obviously less compatible. my design in fact needed the extra gutters, so I removed it.

**Comment by commonpike** [comment]
I now realize the scrollbars would not have appeared if I would have wrapped the content in .container classes. Perhaps something for the documentation.

**Comment by andri** [comment]
@commonpike, thanks for your comment. I will make sure we do a quick doc update when the next version gets released.

**Comment by iocron** [comment]
There is still nothing in the docs about this issue, i have the same problem. @commonpike  What do u mean by "..if i would have wrapped the content in .container divs"? Do you mean "inner container" inside the cols? Or outer ones for the whole thing? I've tried both, it doesn't work :(

@andri is this a bug or are the mentioned containers necessary?

**Comment by andri** [comment]
Hi @iocron, its not a bug. Its a way to prevent the scrollbars because of how the columns and groups work. I have added an section for this to the site. Maybe I have to explain it better?

**Comment by iocron** [comment]
Hello andri,
@andri even if i wrap them around the container (.container) then it still doesn't work. The css class name "container" is too commonly used by a couple other systems already (frameworks, ecommerce shops, etc.), so this might be a issue as well. It's just a suggestion, but would it be possible to add prefixes to your css classes in general? Or even better, use a dynamic variable for adding prefixes to your css classes (more flexibility).

**Comment by andri** [comment]
Container element should wrap around your groups. If you can add your code somewhere I can take a look.

"dynamic variables for adding prefixes"

Yes that would be an option. I have already done this for the new break-points in the 2.0 version  which is the next release. In that version you can customize the prefixes, add and remove break-points in config.

**Comment by andri** [comment]
@iocron, its not perfect I just came across an instance where you see a scrollbar on tablet but not mobile.
