### ISSUE TITLE
col-fixed-square (and probably others) do not work on iOS Devices

### ISSUE THREAD

**Issue by iocron** [andri/fluidable#14]
Hello,
the fixed aspect ratio col-fixed-square and probably the other ones as well do not work on iOS Devices. Instead they have the height of the content. See screenshot below and the following dev site https://www.dergepflegtemanndev.de/marken (problem appeaers on the brand boxes and the footer boxes). Tested with 2 different iOS Devices (iPad & iPad Air).

<img width="770" alt="col-fixed-bug" src="https://cloud.githubusercontent.com/assets/3641649/15998234/e1355304-313c-11e6-8269-33f62bf31dc9.png">

P.S. the docs have an misspelling as well, it should be called ".col-fixed-portrait", but on the current doc site it's ".col-portrait".

Kind regards,
Sebastian P.

**Comment by iocron** [comment]
Weird, the problem appears only on 768px and below. In fluidable.less is the following line: @screenTablet: 	@_screenTablet; (_screenTablet is 48em / 768px), could it be that there gets something specific set that breaks the view?

**Comment by andri** [comment]
The fixed ratio style are not inside a media query, looks like there are some custom styles in your code that are conflicting with Fluidable. There is a line in your CSS that sets margin-top to 0 and then puts the position on the col-content container to relative. Removing these fixes the problem.

**Comment by iocron** [comment]
Hi Andri,
thanks a lot for your tip, that helped. But there is still the width / scrollbar problem on mobile devices even if there is a container class around it (=another bug, mentioned in the "issues" section ("closed") from a while ago, it seems like it is not fixed yet, i had to do a workaround). I'll investigate the problem further (after I've finished the current project) and report it back if i find some more usefull informations about it.

By the way, great less grid system! Love it so far :)

**Comment by andri** [comment]
@iocron thanks! We are working on a new version. Hopefully I will have some time this summer to finish it.
