### ISSUE TITLE
Padding on mobil/tablet states

### ISSUE THREAD

**Issue by Camzilla** [andri/fluidable#16]
I've "downgraded" from bootstrap to fluidable and it's very suitable for the project I'm working on, very nice and lightweight :-) But I'm having an issue throughout the site, I've translated:

(bootstrap / fluidable)
col-xs-x -> col-mb-x
col-sm-x -> col-x
col-md -> col-dt-x
col-lg -> col-ld-x

That means in some places I'll have divs only adapted to the desktop-size. And that means any col-div in tablet and mobile views won't get gutter padding, see example: http://codepen.io/anon/pen/mEgmyY/
The first col-group's children won't be getting padding here.

I can't determine from the documentation that you need to use a specific min col? Only that it is mobile first.

**Comment by andri** [comment]
Hi @Camzilla. The padding style are applied using the col-mb through col-ld classes and their break-points. It definitely a flaw in how Fluidable is designed. Sometimes adding a col-mb-12 works to get around this.
