### ISSUE TITLE
grid on print

### ISSUE THREAD

**Issue by magicwrites** [andri/fluidable#20]
Hello,

I decided to try out fluidable grid system and found it quite okay. However, I cannot make it work on printed documents. Is this by design that all columns gets displayed in separate rows or am I missing something?

Is this okay to expect fluidable grid to work on printed documents?

Cheers and congratulation on a good piece of work,
Maciej

**Comment by andri** [comment]
Hey @magicwrites, how are you linking to your stylesheet? If you are using the media attribute for your linking to your stylesheet make sure it includes print or all.

**Comment by andri** [comment]
You might have to recreate the grid styles in your print CSS stylesheet. See link for similar case using Bootstrap:

http://stackoverflow.com/questions/22199429/bootstrap-grid-for-printing

**Comment by magicwrites** [comment]
You are right, I solved this by adding a `print` media to all of the break points in the stylesheet.

https://github.com/magicwrites/fluidable/commit/b7e19b7612325bd45b43179762e04213df1af3ea

Thank you for helping out.
