### ISSUE TITLE
Expand docs or examples to show FIXED ASPECT RATIO please

### ISSUE THREAD

**Issue by kool-kat** [andri/fluidable#21]
Hi,

I have been struggling to understand the purpose and display results of the FIXED ASPECT RATIO classes.

Would you be able to show them in the docs and/or provide sample code.

I haven't been able to get them working as I am unsure of the differences between each class.

Thanks Kat

**Comment by andri** [comment]
@kool-kat These classes are for to creating things like cards when you want the height and width to be fixed to a specific ratio. Here is an example, to see the effect give the col-content a background color and see how it behaves when you resize the browser window. 

`<div class="col-group">
	<div class="col-4 col-fixed-hd">
		<div class="col-content">
			…
		</div>
	</div>
</div>`
