### ISSUE TITLE
Large screen left space to the right

### ISSUE THREAD

**Issue by aurigadl** [andri/fluidable#23]
Thanks for your job. I am using this for some time.

When used this on screen that have more that 1280px the container left some space to the right.. because having a max-width. I have to delete this line for smart-tv and other screens

@media (min-width: @screenLarge) {
	.container {
		max-width: @screenLarge  - (@gutterWidth * 2);
		.center-block();
	}
....

**Comment by andri** [comment]
Hey, instead of commenting code out you can ether skip the .container class in your markup or overwrite the max-width rule in your own CSS. Using the container class is optional.
