### ISSUE TITLE
http://fluidable.com is down

### ISSUE THREAD

**Issue by ghost** [andri/fluidable#24]
http://fluidable.com isn't accessible anymore.

**Comment by andri** [comment]
Ahh forgot to pay my hosting bill :) Should be online shortly. Thank you for the heads up.

**Comment by andri** [comment]
@coldtelling Everything is back to normal!

**Comment by andri** [comment]
@coldtelling check out the version 2 branch for a flexbox version if you are interested. its beta but should be usable.
