### ISSUE TITLE
Offset classes wrong in documentation?

### ISSUE THREAD

**Issue by bradryanbice** [andri/fluidable#8]
On your website you show the offset classes as **.offset-x** and **.offset-dt-x**, however in fluidable.css I am seeing them as **.col-offset-x** and **.col-dt-offset-x**

Am I missing something here? So, the .col- prefix is missing, and the dt- part is in the wrong place.

Also, why is offset not available for .col-mb-x sizes?

**Comment by andri** [comment]
Yes thanks for pointing that out, the docs are not correct.

**Comment by andri** [comment]
Fixed

**Comment by adammoisa** [comment]
Hi I still don't see offset working for mb?

**Comment by andri** [comment]
@adammoisa Looks like I forgot to include that for the mobile grid. Should be working now. But only for the LESS version.
